feat: add eth_getBlockTransactionCountByNumber
web3-php/web3 pull request #4
Opened 2021-11-24 11:52 UTC by owenvoke

2021-11-24 12:20 UTC, nunomaduro requested changes
Its missing changes in our docs.

2021-11-24 12:20 UTC, nunomaduro commented on src/Namespaces/Eth.php
> +    public function getBlockTransactionCountByNumber(string $blockHash): string
Can you check if we don't accept a number, and we need to translate to hash before sending to the blockchain?

2022-01-06 11:37 UTC, nunomaduro commented
@owenvoke Should I close this?

2022-01-06 11:54 UTC, owenvoke commented
@nunomaduro, apologies, I'll rebase and apply the required changes for this. 👍🏻

2022-01-26 10:39 UTC, merged